# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: edcd2343b355711b303b82786aa8f528adf034082cf4fe00b5df09686e52dd208b68ac30cfae61ad0816d9e7cdbae4575531a9e60b467adecbb81dc759fa3a68

test:
  secret_key_base: 95ab68b9f4c5f1bba11c7d144501899b2f41f8e04c82b1a3c1403683f8469ff8548382aa83e9d98d2a7905d8c58a6958e97c0fa9bd7beceaaa126f588d922dea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
